language: node_js
node_js:
  - '8'

dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build
