dist: trusty
sudo: false

language: node_js
node_js:
  - '14'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install @angular-devkit/build-angular --save-dev
  - npm install

script:
  - npm run test 
  - npm run build
