language: node_js
sudo: required
node_js:
  - '14'

before_script:
  - npm init
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=chromium-browser
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  
