language: node_js
node_js:
  - "8"
  
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - cd Configurations

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
