dist: trusty
sudo: false

language: node_js
node_js:
  - '14'

before_script:
  - npm install
  - export CHROME_BIN=chromium-browser

script:
  - npm run test

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-travisci
